### PR TITLE
Update COPYRIGHT

### PR DESCRIPTION
**Pull request by Parikshit-Hooda**
## Description

updated copyright to include 2019 as covered year too.

## Motivation and Context

part of hacktoberfest.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Final checklist

- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Review by Dillon-Brown — APPROVED** [review]

**Comment by Parikshit-Hooda** [comment]
@Dillon-Brown Please merge this!

**Comment by Dillon-Brown** [comment]
Hi @Parikshit-Hooda, this is actually the first public contribution we've received to the [Pimap](https://github.com/salesagility/Pimap) repository so i'll need to check what our actual process is for merging in PRs. I'll make sure to raise this first thing so we can get it merged in. Thanks!

**Comment by Parikshit-Hooda** [comment]
@Dillon-Brown I shall remind you sometime later, like 3-4 days if no action happens to this pr?

**Comment by Dillon-Brown** [comment]
> @Dillon-Brown I shall remind you sometime later, like 3-4 days if no action happens to this pr?

Yes please! I respond to all direct mentions so feel free to poke me again if it looks like I forgot to progress this.

**Comment by Parikshit-Hooda** [comment]
@Dillon-Brown Please address this now?

**Comment by samus-aran** [comment]
Now just 2020....

**Pull request merged**
